// Shared deterministic road paths and terrain-conforming surface compilation.
const finite=v=>Number.isFinite(+v)?+v:0;
export function cleanRoadPath(path){if(!Array.isArray(path))return null;const out=[];for(const p of path.slice(0,64)){const q={x:Math.max(-600,Math.min(600,finite(p?.x))),z:Math.max(-600,Math.min(600,finite(p?.z)))};if(!out.length||Math.hypot(q.x-out.at(-1).x,q.z-out.at(-1).z)>.05)out.push(q);}return out.length>=2?out:null;}
export function roadNodes(r){const a=(r.rot||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return (cleanRoadPath(r.path)||[{x:-r.w/2,z:0},{x:r.w/2,z:0}]).map(p=>({x:r.x+p.x*c-p.z*s,z:r.z+p.x*s+p.z*c}));}
export function roadSamples(r){const p=roadNodes(r);if(!r.smooth||p.length<3)return p;const out=[p[0]],lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,z:a.z+(b.z-a.z)*t});for(let i=1;i<p.length-1;i++){const a=lerp(p[i-1],p[i],.5),b=lerp(p[i],p[i+1],.5);if(i===1)out.push(a);const n=Math.max(3,Math.min(24,Math.ceil((Math.hypot(a.x-p[i].x,a.z-p[i].z)+Math.hypot(b.x-p[i].x,b.z-p[i].z))/2)));for(let j=1;j<=n;j++){const t=j/n,u=1-t;out.push({x:u*u*a.x+2*u*t*p[i].x+t*t*b.x,z:u*u*a.z+2*u*t*p[i].z+t*t*b.z});}}out.push(p.at(-1));return out;}
export function roadSegments(r){if(!cleanRoadPath(r.path))return [r];const pts=roadSamples(r),out=[];let distance=0;for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],w=Math.hypot(b.x-a.x,b.z-a.z);if(w<.001)continue;out.push({...r,path:undefined,smooth:undefined,x:(a.x+b.x)/2,z:(a.z+b.z)/2,w,d:r.d,rot:Math.atan2(b.z-a.z,b.x-a.x)*180/Math.PI,distance,pathIndex:i});distance+=w;}return out;}
export function roadPolygon(r,width=r.d){const a=(r.rot||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return [[-r.w/2,-width/2],[r.w/2,-width/2],[r.w/2,width/2],[-r.w/2,width/2]].map(([x,z])=>({x:r.x+x*c-z*s,z:r.z+x*s+z*c}));}
// Positive winding convex polygon clipping. Each output triangle stays within a single terrain triangle.
function clip(poly,a,b){const side=p=>(b.x-a.x)*(p.z-a.z)-(b.z-a.z)*(p.x-a.x),out=[];for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],sp=side(p),sq=side(q),inside=sp>=-1e-9;if(inside)out.push(p);if(inside!==(sq>=-1e-9)){const t=sp/(sp-sq);out.push({x:p.x+(q.x-p.x)*t,z:p.z+(q.z-p.z)*t});}}return out;}
export function appendTerrainRoad(data,polygon,terrain,offset=.018){if(polygon.length<3)return;const size=terrain.TERRAIN_SIZE,n=terrain.TERRAIN_SEGMENTS,step=size/n,half=size/2,idx=v=>Math.max(0,Math.min(n-1,Math.floor((v+half)/step))),x0=idx(Math.min(...polygon.map(p=>p.x))),x1=idx(Math.max(...polygon.map(p=>p.x))),z0=idx(Math.min(...polygon.map(p=>p.z))),z1=idx(Math.max(...polygon.map(p=>p.z)));for(let iz=z0;iz<=z1;iz++)for(let ix=x0;ix<=x1;ix++){const x=-half+ix*step,z=-half+iz*step,a={x,z},b={x:x+step,z},c={x,z:z+step},d={x:x+step,z:z+step};for(const tri of [[a,b,c],[b,d,c]]){let p=polygon;for(let k=0;k<3&&p.length;k++)p=clip(p,tri[k],tri[(k+1)%3]);if(p.length<3)continue;const base=data.positions.length/3;for(const v of p){data.positions.push(v.x,terrain.terrainHeight(v.x,v.z)+offset,v.z);data.uvs.push(v.x/8,v.z/8);}for(let k=1;k<p.length-1;k++)data.indices.push(base,base+k+1,base+k);}}}
// Remove a convex footprint from another polygon, retaining disjoint outside pieces.
export function subtractRoadPolygon(polygon,cut){let inside=polygon;const pieces=[];for(let i=0;i<cut.length&&inside.length;i++){const a=cut[i],b=cut[(i+1)%cut.length],outside=clip(inside,b,a);if(outside.length>=3)pieces.push(outside);inside=clip(inside,a,b);}return pieces;}
