import { resolveAsset } from './object-catalog.js';
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const text=(v,max=64,f='')=>String(v??f).replace(/[\u0000-\u001f\u007f]/g,'').slice(0,max);
const arr=(v,max)=>Array.isArray(v)?v.slice(0,max):[];
const rot=v=>{let r=finite(v)%360;if(r<0)r+=360;return r;};
const point=(p,arena)=>Array.isArray(p)&&p.length>=2?[clamp(finite(p[0]),-arena,arena),clamp(finite(p[1]),-arena,arena),clamp(finite(p[2]),-10,30),rot(p[3])]:null;
const PROP_KIND_ALIASES=Object.freeze({car:'burntCar',bus:'burntBus',brokenwall:'brokenWall',fueltank:'fuelTank',pipebank:'pipe',box:'crate'});
export function canonicalPropKind(value){const raw=String(value||'').trim();return PROP_KIND_ALIASES[raw]||raw||'crate';}
function ladderFrame(o){const rx=finite(o?.nx),rz=finite(o?.nz),len=Math.hypot(rx,rz);if(!Number.isFinite(len)||len<.25)return null;const nx=rx/len,nz=rz/len;return{nx,nz,tx:-nz,tz:nx};}
export const MAX_CUSTOM_MAP_BYTES=900000;
export const CUSTOM_MAP_SCHEMA='breach-authored-map';
export const CUSTOM_MAP_SCHEMA_VERSIONS=Object.freeze([1,2,3]);
export function customMapSerializedSize(raw){try{return new TextEncoder().encode(JSON.stringify(raw)).length}catch{try{return JSON.stringify(raw).length}catch{return Infinity}}}
export function customMapFingerprint(raw){const s=typeof raw==='string'?raw:JSON.stringify(raw);let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0;}return h.toString(16).padStart(8,'0');}
function heightfield(raw,arena){if(!raw||typeof raw!=='object')return null;const size=clamp(Math.round(finite(raw.size,0)),9,129),extent=clamp(finite(raw.extent,arena),20,arena),values=Array.isArray(raw.values)?raw.values:null;if(!values||values.length!==size*size)return null;return{size,extent,values:values.map(v=>clamp(finite(v),-30,30))};}
function materials(raw,arena){if(!raw||typeof raw!=='object')return null;const size=clamp(Math.round(finite(raw.size,0)),9,129),extent=clamp(finite(raw.extent,arena),20,arena),values=Array.isArray(raw.values)?raw.values:null;if(!values||values.length!==size*size)return null;return{size,extent,values:values.map(v=>clamp(Math.round(finite(v)),0,8))};}
function scalars(obj,maxKeys=96){const out={};if(!obj||typeof obj!=='object'||Array.isArray(obj))return out;for(const [k,v] of Object.entries(obj).slice(0,maxKeys)){const key=text(k,48);if(!key)continue;if(typeof v==='boolean')out[key]=v;else if(typeof v==='number'&&Number.isFinite(v))out[key]=clamp(v,-1e9,1e9);else if(typeof v==='string')out[key]=text(v,96);}return out;}
export function sanitizeUploadedMapDefinition(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Invalid map file.');
 if(raw.schema!==CUSTOM_MAP_SCHEMA)throw new Error('This is not a Breach authored map.');
 const version=Math.round(finite(raw.schemaVersion,1));if(!CUSTOM_MAP_SCHEMA_VERSIONS.includes(version))throw new Error(`Unsupported map schema ${version}.`);
 const bytes=customMapSerializedSize(raw);if(!Number.isFinite(bytes)||bytes>MAX_CUSTOM_MAP_BYTES)throw new Error(`Map file is too large (${Math.ceil(bytes/1024)} KB; max ${Math.floor(MAX_CUSTOM_MAP_BYTES/1024)} KB).`);
 const arena=clamp(finite(raw.arenaLimit,120),30,300),mini=clamp(finite(raw.minimapLimit,Math.min(arena,120)),20,arena),theme=['flat','highlands','depot','yard','rig'].includes(String(raw.theme))?String(raw.theme):'flat';
 const clean={schema:CUSTOM_MAP_SCHEMA,schemaVersion:version,creatorVersion:text(raw.creatorVersion,32),sourceRelease:text(raw.sourceRelease,32),meta:{id:text(raw.meta?.id||'custom-map',48,'custom-map'),name:text(raw.meta?.name||'CUSTOM MAP',64,'CUSTOM MAP')},theme,arenaLimit:arena,minimapLimit:mini};
 const terrainRaw=raw.terrain&&typeof raw.terrain==='object'?raw.terrain:{};const hf=heightfield(terrainRaw.heightfield||raw.heightfield,arena),mat=materials(terrainRaw.materials||raw.materials,arena);clean.terrain={preset:['flat','highlands','depot','yard','rig'].includes(String(terrainRaw.preset))?String(terrainRaw.preset):theme};if(hf)clean.terrain.heightfield=hf;if(mat)clean.terrain.materials=mat;
 const mods=arr(terrainRaw.modifiers||raw.terrainModifiers,256).map(o=>({kind:['hill','valley','plateau','pit'].includes(String(o?.kind))?String(o.kind):'hill',x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),radius:clamp(finite(o?.radius,16),3,100),height:clamp(finite(o?.height,3),-24,30)}));if(mods.length)clean.terrain.modifiers=mods;
 clean.environment={preset:text(raw.environment?.preset,16,'day'),weather:text(raw.environment?.weather,16,'clear'),sunAzimuth:rot(raw.environment?.sunAzimuth),sunElevation:clamp(finite(raw.environment?.sunElevation,48),-30,85),cloudAmount:clamp(finite(raw.environment?.cloudAmount,0),0,1),fogAmount:clamp(finite(raw.environment?.fogAmount,0),0,.85),rainIntensity:clamp(finite(raw.environment?.rainIntensity,0),0,1),ambient:clamp(finite(raw.environment?.ambient,.72),.12,1),wetness:clamp(finite(raw.environment?.wetness,0),0,1),wind:clamp(finite(raw.environment?.wind,.15),0,1)};
 clean.roads=arr(raw.roads,256).map(o=>({kind:['street','alley','service','dirt','sidewalk','crosswalk'].includes(String(o?.kind))?String(o.kind):'street',x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),w:clamp(finite(o?.w,20),2,600),d:clamp(finite(o?.d,8),1,40),rot:rot(o?.rot)}));
 clean.staticBoxes=arr(raw.staticBoxes||raw.props,512).map(o=>resolveAsset(o,'prop')).map(o=>({assetId:o.assetId,x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),w:clamp(finite(o?.w,2),.3,80),d:clamp(finite(o?.d,2),.3,80),h:clamp(finite(o?.h,2),.2,40),rot:rot(o?.rot),yOffset:clamp(finite(o?.yOffset),-12,30),kind:canonicalPropKind(o?.kind)}));
 clean.buildings=arr(raw.buildings,128).map(o=>resolveAsset(o,'building')).map(o=>({assetId:o.assetId,archetype:o.archetype,x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),w:clamp(finite(o?.w,18),8,80),d:clamp(finite(o?.d,14),6,80),floorH:clamp(finite(o?.floorH,3.1),2.2,5),balcony:clamp(finite(o?.balcony,0),0,10),levels:clamp(Math.round(finite(o?.levels,2)),1,8),rot:rot(o?.rot),yOffset:clamp(finite(o?.yOffset),-12,30),style:text(o?.style,24,'industrial'),...(o?.tall?{tall:true}:{})}));
 clean.elevationObjects=arr(raw.elevationObjects||raw.elevation,128).map(o=>resolveAsset(o,'elevation')).map(o=>({assetId:o.assetId,kind:['platform','ramp','stairs','overpass'].includes(String(o?.kind))?String(o.kind):'platform',x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),w:clamp(finite(o?.w,8),2,80),d:clamp(finite(o?.d,10),2,100),rise:clamp(finite(o?.rise,3),.5,24),rot:rot(o?.rot),yOffset:clamp(finite(o?.yOffset),-8,20)}));
 clean.pyramids=arr(raw.pyramids||raw.mounds,128).map(o=>({x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),base:clamp(finite(o?.base,8),2,60),h:clamp(finite(o?.h,4),.5,30)}));
 clean.naturalObstacles=arr(raw.naturalObstacles||raw.naturals,256).map(o=>({type:['tree','bush','rock'].includes(String(o?.type||o?.kind))?String(o.type||o.kind):'rock',x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),r:clamp(finite(o?.r,1),.2,12),h:clamp(finite(o?.h,1),.2,40)}));
 clean.ladders=arr(raw.ladders,128).map((o,i)=>{const frame=ladderFrame(o);if(!frame)return null;return{id:text(o?.id,48,`ladder-${i+1}`),x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena),...frame,width:clamp(finite(o?.width,1.2),.5,4),bottomY:clamp(finite(o?.bottomY),-30,80),topY:clamp(finite(o?.topY,3),-29,100)};}).filter(o=>o&&o.topY>o.bottomY+.4);
 clean.combatFlowNodes=arr(raw.combatFlowNodes||raw.flowNodes||raw.flow,512).map(o=>({x:clamp(finite(o?.x),-arena,arena),z:clamp(finite(o?.z),-arena,arena)}));
 const sp=raw.spawnSets||raw.spawns||{},teams={};for(const k of ['blue','red','ffa'])teams[k]=arr(sp[k],96).map(p=>point(p,arena)).filter(Boolean);clean.spawnSets=teams;clean.spawnPolicy=scalars(raw.spawnPolicy,128);
 return clean;
}
export function sanitizeBuilderDraftDefinition(raw){
 const clean=sanitizeUploadedMapDefinition(raw),sourceGroups=raw?.editor?.groups&&typeof raw.editor.groups==='object'&&!Array.isArray(raw.editor.groups)?raw.editor.groups:{},meta=(dst,src,{yOffset=false,archetype=false,parent=false}={})=>{if(!dst||!src||typeof src!=='object')return;const id=text(src.id,48);if(id)dst.id=id;const groupId=text(src.groupId||sourceGroups[id],48);if(groupId)dst.groupId=groupId;if(yOffset)dst.yOffset=clamp(finite(src.yOffset),-12,30);if(archetype){const a=text(src.archetype,24);if(a)dst.archetype=a}if(parent){const parentId=text(src.parentId,48);if(parentId)dst.parentId=parentId;const side=['e','w','n','s'].includes(String(src.side))?String(src.side):'';if(side)dst.side=side;dst.t=clamp(finite(src.t),-.45,.45)}};
 const roadSrc=arr(raw.roads,256);clean.roads.forEach((o,i)=>meta(o,roadSrc[i],{yOffset:true}));
 const boxSrc=arr(raw.staticBoxes||raw.props,512);clean.staticBoxes.forEach((o,i)=>meta(o,boxSrc[i]));
 const buildingSrc=arr(raw.buildings,128);clean.buildings.forEach((o,i)=>meta(o,buildingSrc[i],{archetype:true}));
 const elevationSrc=arr(raw.elevationObjects||raw.elevation,128);clean.elevationObjects.forEach((o,i)=>meta(o,elevationSrc[i]));
 const moundSrc=arr(raw.pyramids||raw.mounds,128);clean.pyramids.forEach((o,i)=>meta(o,moundSrc[i]));
 const naturalSrc=arr(raw.naturalObstacles||raw.naturals,256);clean.naturalObstacles.forEach((o,i)=>meta(o,naturalSrc[i]));
 const flowSrc=arr(raw.combatFlowNodes||raw.flowNodes||raw.flow,512);clean.combatFlowNodes.forEach((o,i)=>meta(o,flowSrc[i]));
 const ladderSrc=arr(raw.ladders,128),byLadderId=new Map(ladderSrc.map((o,i)=>[text(o?.id,48,`ladder-${i+1}`),o]));clean.ladders.forEach((o,i)=>meta(o,byLadderId.get(o.id)||ladderSrc[i],{parent:true}));
 const spawnSrc=raw.spawnSets||raw.spawns||{};for(const team of ['blue','red','ffa']){const src=arr(spawnSrc[team],96),dst=clean.spawnSets[team]||[];for(let i=0;i<dst.length;i++){const p=src[i];if(!Array.isArray(p))continue;const id=text(p[4],48),groupId=text(p[5],48);if(id)dst[i].push(id);if(groupId){if(!id)dst[i].push('');dst[i].push(groupId)}}}
 if(raw.editor&&typeof raw.editor==='object'&&!Array.isArray(raw.editor)){const editor=scalars(raw.editor,96),groups={};if(raw.editor.groups&&typeof raw.editor.groups==='object'&&!Array.isArray(raw.editor.groups))for(const [k,v] of Object.entries(raw.editor.groups).slice(0,1024)){const id=text(k,48),group=text(v,48);if(id&&group)groups[id]=group}if(Object.keys(groups).length)editor.groups=groups;const runtime=scalars(raw.editor.runtime,32);if(Object.keys(runtime).length)editor.runtime=runtime;clean.editor=editor}
 return clean;
}
export function customMapSummary(def){const d=sanitizeUploadedMapDefinition(def);return{name:d.meta.name,id:d.meta.id,schemaVersion:d.schemaVersion,arenaLimit:d.arenaLimit,minimapLimit:d.minimapLimit,roads:d.roads.length,buildings:d.buildings.length,props:d.staticBoxes.length,spawns:(d.spawnSets.blue?.length||0)+(d.spawnSets.red?.length||0),bytes:customMapSerializedSize(d)};}
